### ISSUE TITLE
Question: Is URL likely to be permanent?

### ISSUE THREAD

**Issue by smach** [holtzy/Pimp-my-rmd#1]
Hi. I'm writing a book about R and would like to include the link to Pimp my RMD at https://holtzy.github.io/Pimp-my-rmd/ . I realize no one can predict the future, but is that likely to be a fairly permanent URL for a couple of years? Thanks.

**Comment by holtzy** [comment]
Hi @smach, 
Thanks for your interest, this URL is likely to be permanent.
I just plan to improve it when I discover new useful tips!
Cheers
