### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kent37** [holtzy/Pimp-my-rmd#2]
Here are some of my favorite markdown tweaks.

- To default to printing tables using `knitr::kable`, add `df_print: kable` to the YAML header.
https://rmarkdown.rstudio.com/html_document_format.html#data_frame_printing

- By default, `kable` output is spread across the full width of the page. I add this CSS snippet to make `kable` output more compact.
```
table {
  width: auto !important;
}
```

- You can change the output theme easily with the `theme` parameter in the YAML header. This allows easy selection of any of the Bootswatch 3 themes.
https://rmarkdown.rstudio.com/html_document_format.html#appearance_and_style
Theme examples here:
https://bootswatch.com/3/

**Comment by holtzy** [comment]
Hi @kent37,

Thanks for your feedback. I just added a new section concerning the theme and highlight options. However I'm a big fan of the DT table package so I will stick to it yet.

Thanks for your contribution!
